version: "3.9"
name: ssh_vpn

services:
  sshd:
    build: .
    restart: unless-stopped
    mem_limit: 128M
    ports:
      - "0.0.0.0:443:22"
    volumes:
      - ./config/sshd_config:/etc/ssh/sshd_config:ro
