name: ssh_vpn

services:
  sshd:
    build: ./docker
    restart: unless-stopped
    mem_limit: 128M
    ports:
      - "0.0.0.0:2202:22"
      - "[::]:2202:22"
    volumes:
      - ./config/sshd_config:/etc/ssh/sshd_config:ro
      - type: bind
        source: ./credentials
        target: /run/secrets/credentials
        read_only: true
        bind:
          create_host_path: false
